const translations = {
  en: {
    "meta_desc": "A graphic and video design studio based in Whitehorse. Specializing in brand identity, sleek digital aesthetics, and professional print.",
    "nav_portfolio": "Portfolio",
    "nav_services": "Services",
    "nav_contact": "Contact",
    "nav_cta": "Start a Project",
    "lang_toggle": "FR",
    "hero_label_est": "Est. 2021",
    "hero_label_studio": "Design Studio",
    "hero_headline": "HEAVY<br><em class=\"hero-accent\">COMPUTER</em><br>WORK.",
    "hero_body": "Collarwork is a creative studio specialized in graphic design. We consider our work like the craft that builds the visual infrastructure of your project.",
    "hero_cta": "Start a Project",
    "about_label": "About",
    "about_statement": "We are established in the Yukon, where the rugged work ethic of the North meets creative liberation. A hands-on problem-solving approach is what graphic design is to us. We execute technical creative work across print and digital platforms, managing the entire process from initial branding to final post-production. Your project and ideas are meant to live.",
    "about_stat_1": "Projects<br>Shipped",
    "about_stat_2": "Clients",
    "about_stat_3": "Languages",
    "portfolio_label": "Selected Clients",
    "portfolio_subtext": "Here are a few curated clients with who we have done some projects to display our work.",
    "port_01_label": "Illustration",
    "port_01_desc": "With the goal to reach a new audience during a large scale event happening in Whitehorse, <i>l'Aurore boréale</i> wa looking for a design that felt fresh and could reach a younger audience.",
    "port_01_tag1": "DESIGN",
    "port_01_tag2": "STICKERS",
    "port_02_label": "Branding",
    "port_02_desc": "This local business in the tourism industry, became Wild up, a fully established brand. We built the brand, starting with the name to every other details.",
    "port_02_tag1": "BRANDING",
    "port_02_tag2": "DESIGN",
    "port_03_label": "Branding",
    "port_03_desc": "Handcrafted creation deserve a handcrafted design for their brand. This skilled artisan needed an image that could handle her imagination",
    "port_03_tag1": "BRANDING",
    "port_03_tag2": "DESIGN",
    "port_04_label": "Graphic Design",
    "port_04_desc": "A common collaboration with the Société d'hisoitre francophone du Yukon to create, edit develop their ideas and expos.",
    "port_04_tag1": "LOCAL",
    "port_04_tag2": "DIGITAL",
    "port_04_title": "Société d'histoire francophone du Yukon",
    "port_05_label": "Case Study",
    "port_05_desc": "Currently in development. Coming soon.",
    "port_05_tag1": "SYSTEMS",
    "port_05_tag2": "PRINT",
    "port_05_title": "Project Epsilon",
    "services_label": "Services",
    "services_subtext": "Select a service. We'll grab the tools and map out your blueprint.",
    "serv_01_title": "Graphic Design",
    "serv_01_desc": "Handling high-volume documents and physical media. From multi-page manuals and reports to newspaper ads and signage, we build print-ready files that do the heavy lifting for your business.",
    "serv_01_tag2": "EDITORIAL",
    "serv_01_tag3": "PRINT",
    "serv_02_title": "Branding Blueprint",
    "serv_02_desc": "Honest, scalable identities built for the long haul. We draft the logos, brand systems, and visual assets your business needs to show up professionally and stand out locally.",
    "serv_02_tag2": "IDENTITY",
    "serv_02_tag3": "BRANDING",
    "serv_03_title": "Video Production",
    "serv_03_desc": "On-site documentation and straightforward storytelling. We handle the shooting and editing for interviews, event coverage, and promotional ads, delivering polished photo and video content ready for your audience.",
    "serv_03_tag2": "VIDEO",
    "serv_03_tag3": "PHOTOGRAPHY",
    "contact_label": "New Inquiry",
    "contact_headline": "LET'S BUILD<br>SOMETHING<br>THAT LASTS.",
    "contact_subtext": "We're built on the handshake. Tell us your goals, and we'll bring the hard work and integrity to make it happen.",
    "contact_info": "hello@collarworkdesign.com<br><a href=\"https://www.instagram.com/collarworkdesign/\" target=\"_blank\" rel=\"noopener noreferrer\">@collarworkdesign</a><br>Yukon | Québec",
    "form_label_name": "Full Name",
    "form_label_email": "Email Address",
    "form_label_subject": "Subject",
    "form_label_brief": "Project Brief",
    "form_placeholder_name": "Your name",
    "form_placeholder_email": "you@company.com",
    "form_placeholder_brief": "Tell us about your project, timeline, and goals.",
    "form_subject_default": "Select a subject",
    "form_subj_1": "Brand Identity & Logo Design",
    "form_subj_2": "Print Layout & Typography",
    "form_subj_3": "Video Production & Editing",
    "form_subj_4": "Photography & Retouching",
    "form_subj_5": "Documents: Manuals, annual reports, booklets, and more.",
    "form_subj_6": "Print: Posters, newspaper ads, signage, stickers, and more.",
    "form_subj_7": "Digital Media.",
    "form_subj_8": "Some other crazy idea",
    "form_submit": "Send Brief",
    "contact_promo_btn": "Start Project",
    "footer_tagline": "From the north.",
    "footer_nav": "Navigation",
    "footer_legal": "Legal",
    "footer_social": "Social",
    "footer_link_privacy": "Privacy Policy",
    "footer_link_terms": "Terms of Service",
    "footer_copy_1": "© 2026 Collarwork<br>All rights reserved.",
    "footer_copy_2": "Built with precision."
    ,
    "contact_hero_label": "New Inquiry",
    "contact_hero_headline": "Let&apos;s Start<br><em class=\"hero-accent\">Your Project</em>",
    "contact_hero_subtext": "Tell us about your vision. We&apos;ll bring the expertise and dedication to make it reality.",
    "contact_info_label_1": "Get In Touch",
    "contact_info_label_2": "Response Time",
    "contact_info_text_2": "We typically respond within 24-48 hours during business days.",
    "contact_info_label_3": "What Happens Next?",
    "contact_process_1": "We review your inquiry",
    "contact_process_2": "Schedule a discovery call",
    "contact_process_3": "Prepare a custom proposal",
    "contact_process_4": "Begin the creative work",
    "form_success_title": "Message Sent Successfully",
    "form_success_msg": "Thank you for reaching out. We&apos;ll get back to you within 24-48 hours.",
    "form_success_btn": "Send Another Message",
    "form_error_title": "Something Went Wrong",
    "form_error_msg": "There was an error sending your message. Please try again or email us directly.",
    "form_error_btn": "Try Again",

    "form_sec_1_title": "Who are you?",
    "c_form_label_name": "Full Name <span class=\"required-star\">*</span>",
    "c_form_err_name": "Please enter your name",
    "c_form_label_email": "Email Address <span class=\"required-star\">*</span>",
    "c_form_err_email": "Please enter a valid email address",
    "c_form_label_company": "Company / Organization",
    "c_form_label_phone": "Phone Number",

    "form_sec_2_title": "What do you need?",
    "c_form_label_type": "Project Type <span class=\"required-star\">*</span>",
    "c_form_err_type": "Please select a project type",
    "c_form_type_1": "Brand Identity and Logo Design",
    "c_form_type_2": "Print Layout and Typography",
    "c_form_type_3": "Video Production and Editing",
    "c_form_type_4": "Photography and Retouching",
    "c_form_type_5": "Documents (Manuals, Reports, Booklets)",
    "c_form_type_6": "Print Materials (Posters, Signage, Stickers)",
    "c_form_type_7": "Digital Media and Social Content",
    "c_form_type_8": "Website Design",
    "c_form_type_9": "Something Else",
    "c_form_label_title": "Project Title / Name <span class=\"required-star\">*</span>",
    "c_form_err_title": "Don't worry. Please give your project a simple name",

    "form_sec_3_title": "Why this project?",
    "c_form_label_goals": "What are you trying to achieve? <span class=\"required-star\">*</span>",
    "c_form_hint_goals": "Describe the purpose, target audience, and desired outcome of this project.",
    "c_form_err_goals": "Please describe your project goals",
    "c_form_label_insp": "Any inspiration or references?",
    "c_form_hint_insp": "Links, brands, styles, or examples you admire. This helps us understand your vision.",

    "form_sec_4_title": "When do you need it?",
    "c_form_label_urgency": "Timeline <span class=\"required-star\">*</span>",
    "c_form_err_urgency": "Please select a timeline",
    "c_form_urgency_1": "Flexible Timeline",
    "c_form_urgency_2": "Within 1-2 Weeks",
    "c_form_urgency_3": "Within 1 Month",
    "c_form_urgency_4": "2-3 Months",
    "c_form_urgency_5": "As Soon As Possible",
    "c_form_label_deadline": "Hard Deadline (if any)",

    "form_sec_5_title": "What&apos;s your budget?",
    "c_form_label_budget": "Budget Range <span class=\"required-star\">*</span>",
    "c_form_hint_budget": "This helps us scope the project appropriately. We&apos;ll discuss specifics during our call.",
    "c_form_err_budget": "Please select a budget range",
    "c_form_budg_1": "Under $500",
    "c_form_budg_2": "$500 - $1,000",
    "c_form_budg_3": "$1,000 - $2,500",
    "c_form_budg_4": "$2,500 - $5,000",
    "c_form_budg_5": "$5,000 - $10,000",
    "c_form_budg_6": "Over $10,000",
    "c_form_budg_7": "Not Sure Yet",

    "form_sec_6_title": "Anything else?",
    "c_form_label_add": "Additional details or questions",
    "c_form_hint_add": "Files, constraints, special requirements, or questions you have for us.",
    "c_form_label_found": "How did you find us?",
    "c_form_found_1": "Search Engine",
    "c_form_found_2": "Social Media",
    "c_form_found_3": "Referral / Word of Mouth",
    "c_form_found_4": "Returning Client",
    "c_form_found_5": "Event / Conference",
    "c_form_found_6": "Other",

    "c_form_btn_text": "Send Project Brief",
    "c_form_btn_loading": "Sending...",
    "c_form_disclaimer": "By submitting, you agree to our <a href=\"privacy.html\">Privacy Policy</a>.",
  },
  fr: {
    "meta_desc": "Un studio de design graphique et vidéo basé à Whitehorse. Spécialisé en image de marque, esthétique numérique épurée et impression professionnelle.",
    "nav_portfolio": "Réalisations",
    "nav_services": "Services",
    "nav_contact": "Contact",
    "nav_cta": "Démarrer un projet",
    "lang_toggle": "EN",
    "hero_label_est": "Est. 2021",
    "hero_label_studio": "Studio de design",
    "hero_headline": "UNE GROSSE JOB<br><em class=\"hero-accent\">D'ORDINATEUR.</em>",
    "hero_body": "Collarwork est un studio de création spécialisé en design graphique. Nous considérons notre travail comme le métier d’artisan qui construit l'infrastructure visuelle de votre projet.",
    "hero_cta": "Démarrer un projet",
    "about_label": "À propos",
    "about_statement": "Nous sommes établis au Yukon, où l'éthique de travail robuste du Nord rencontre la libération créative. Nous abordons le design graphique comme un travail pratique de résolution de problèmes.",
    "about_stat_1": "Projets<br>Livrés",
    "about_stat_2": "Clients",
    "about_stat_3": "Langues",
    "portfolio_label": "Réalisations",
    "portfolio_subtext": "Un aperçu de nos marques robustes, interfaces techniques durables et identités honnêtes.",
    "port_01_label": "Illustration",
    "port_01_desc": "Dans le but d'atteindre un nouveau public lors d'un événement à grande échelle se déroulant à Whitehorse, <i>l'Aurore boréale</i> cherchait un design frais pouvant rejoindre un public plus jeune.",
    "port_01_tag1": "DESIGN",
    "port_01_tag2": "AUTOCOLLANTS",
    "port_02_label": "Image de marque",
    "port_02_desc": "Cette entreprise locale de l'industrie touristique est devenue Wild up, une marque pleinement établie. Nous avons bâti la marque, en commençant par le nom jusqu'à tous les autres détails.",
    "port_02_tag1": "IDENTITÉ",
    "port_02_tag2": "DESIGN",
    "port_03_label": "Image de marque",
    "port_03_desc": "Les créations artisanales méritent un design artisanal pour leur marque. Cette artisane qualifiée avait besoin d'une image à la hauteur de son imagination.",
    "port_03_tag1": "IDENTITÉ",
    "port_03_tag2": "MARQUE",
    "port_04_label": "Design Graphique",
    "port_04_desc": "Une collaboration commune avec la Société d'histoire francophone du Yukon pour créer, éditer et développer leurs idées et expositions.",
    "port_04_tag1": "LOCAL",
    "port_04_tag2": "NUMÉRIQUE",
    "port_04_title": "Société d'histoire francophone du Yukon",
    "port_05_label": "Étude de cas",
    "port_05_desc": "Actuellement en développement. À venir.",
    "port_05_tag1": "SYSTÈMES",
    "port_05_tag2": "IMPRESSION",
    "port_05_title": "Projet Epsilon",
    "services_label": "Services",
    "services_subtext": "Sélectionnez un service. On sort les outils et on trace votre plan.",
    "serv_01_title": "Design Graphique",
    "serv_01_desc": "Gestion de documents à grand volume et de supports physiques. Des manuels et rapports de plusieurs pages aux publicités de journaux et enseignes, nous bâtissons des fichiers prêts pour l'impression qui font le gros du travail pour votre entreprise.",
    "serv_01_tag2": "ÉDITORIAL",
    "serv_01_tag3": "IMPRESSION",
    "serv_02_title": "Images de Marque",
    "serv_02_desc": "Des identités honnêtes et évolutives, bâties pour durer. Nous concevons les logos, systèmes de marque et actifs visuels dont votre entreprise a besoin pour se présenter de manière professionnelle et se démarquer localement.",
    "serv_02_tag2": "IDENTITÉ",
    "serv_02_tag3": "BRANDING",
    "serv_03_title": "Production Vidéo",
    "serv_03_desc": "Documentation sur site et storytelling direct. Nous gérons le tournage et le montage d'entrevues, la couverture d'événements et les publicités promotionnelles, en livrant un contenu photo et vidéo soigné, prêt pour votre public.",
    "serv_03_tag2": "VIDÉO",
    "serv_03_tag3": "PHOTOGRAPHIE",
    "contact_label": "Nouvelle Demande",
    "contact_headline": "BÂTISSONS<br>QUELQUE CHOSE<br>QUI DURE.",
    "contact_subtext": "On base tout sur une bonne poignée de main. Parlez-nous de vos objectifs, et on amènera le travail acharné et l'intégrité pour les réaliser.",
    "contact_info": "hello@collarworkdesign.com<br><a href=\"https://www.instagram.com/collarworkdesign/\" target=\"_blank\" rel=\"noopener noreferrer\">@collarworkdesign</a><br>Yukon | Québec",
    "form_label_name": "Nom complet",
    "form_label_email": "Courriel",
    "form_label_subject": "Sujet",
    "form_label_brief": "Détails du projet",
    "form_placeholder_name": "Votre nom",
    "form_placeholder_email": "vocre@compagnie.com",
    "form_placeholder_brief": "Décrivez-nous votre projet, votre échéancier et vos buts.",
    "form_subject_default": "Sélectionnez un sujet",
    "form_subj_1": "Images de marque & Design de logo",
    "form_subj_2": "Mise en page imprimée & Typographie",
    "form_subj_3": "Production vidéo & Montage",
    "form_subj_4": "Photographie & Retouche",
    "form_subj_5": "Documents : Manuels, rapports annuels, livrets, et plus.",
    "form_subj_6": "Print : Affiches, publicités, enseignes, autocollants, et plus.",
    "form_subj_7": "Visuels digitaux.",
    "form_subj_8": "Une autre idée de fou",
    "form_submit": "Envoyer",
    "contact_promo_text": "Prêt à commencer ? Remplissez notre formulaire de projet détaillé, et créons quelque chose d&apos;incroyable ensemble.",
    "contact_promo_btn": "Commencer le projet",
    "footer_tagline": "C'est le nord.",
    "footer_nav": "Navigation",
    "footer_legal": "Légal",
    "footer_social": "Réseaux sociaux",
    "footer_link_privacy": "Politique de confidentialité",
    "footer_link_terms": "Conditions générales",
    "footer_copy_1": "© 2026 Collarwork<br>Tous droits réservés.",
    "footer_copy_2": "Bâti avec précision."
    ,
    "contact_hero_label": "Nouvelle Demande",
    "contact_hero_headline": "Démarrons<br><em class=\"hero-accent\">Votre Projet</em>",
    "contact_hero_subtext": "Parlez-nous de votre vision. Nous apporterons l&apos;expertise et le dévouement pour la réaliser.",
    "contact_info_label_1": "Contactez-nous",
    "contact_info_label_2": "Délai de réponse",
    "contact_info_text_2": "Nous répondons généralement dans un délai de 24 à 48 heures ouvrables.",
    "contact_info_label_3": "Quelles sont les prochaines étapes ?",
    "contact_process_1": "Nous examinons votre demande",
    "contact_process_2": "Appel de découverte",
    "contact_process_3": "Préparation d'une proposition sur mesure",
    "contact_process_4": "Début du travail créatif",
    "form_success_title": "Message envoyé avec succès",
    "form_success_msg": "Merci de nous avoir contactés. Nous vous reviendrons sous 24-48 heures.",
    "form_success_btn": "Envoyer un autre message",
    "form_error_title": "Un problème est survenu",
    "form_error_msg": "Une erreur est survenue lors de l'envoi. Veuillez réessayer ou nous envoyer un courriel directement.",
    "form_error_btn": "Réessayer",

    "form_sec_1_title": "Qui êtes-vous ?",
    "c_form_label_name": "Nom complet <span class=\"required-star\">*</span>",
    "c_form_err_name": "Veuillez entrer votre nom",
    "c_form_label_email": "Courriel <span class=\"required-star\">*</span>",
    "c_form_err_email": "Veuillez entrer un courriel valide",
    "c_form_label_company": "Entreprise / Organisation",
    "c_form_label_phone": "Numéro de téléphone",

    "form_sec_2_title": "De quoi avez-vous besoin ?",
    "c_form_label_type": "Type de projet <span class=\"required-star\">*</span>",
    "c_form_err_type": "Veuillez sélectionner un type de projet",
    "c_form_type_1": "Image de marque et Création de logo",
    "c_form_type_2": "Mise en page imprimée et Typographie",
    "c_form_type_3": "Production vidéo et Montage",
    "c_form_type_4": "Photographie et Retouche",
    "c_form_type_5": "Documents (Manuels, Rapports, Livrets)",
    "c_form_type_6": "Matériel Imprimé (Affiches, Enseignes, Autocollants)",
    "c_form_type_7": "Médias numériques et Contenu social",
    "c_form_type_8": "Conception de site web",
    "c_form_type_9": "Autre chose",
    "c_form_label_title": "Titre du projet / Nom <span class=\"required-star\">*</span>",
    "c_form_err_title": "Veuillez donner un nom à votre projet",

    "form_sec_3_title": "Pourquoi ce projet ?",
    "c_form_label_goals": "Qu'essayez-vous d'accomplir ? <span class=\"required-star\">*</span>",
    "c_form_hint_goals": "Décrivez le but, le public cible et le résultat souhaité de ce projet.",
    "c_form_err_goals": "Veuillez décrire les objectifs de votre projet",
    "c_form_label_insp": "Avez-vous des inspirations ou des références ?",
    "c_form_hint_insp": "Liens, marques, styles ou exemples que vous admirez. Cela nous aide à comprendre votre vision.",

    "form_sec_4_title": "Quand en avez-vous besoin ?",
    "c_form_label_urgency": "Échéancier <span class=\"required-star\">*</span>",
    "c_form_err_urgency": "Veuillez sélectionner un échéancier",
    "c_form_urgency_1": "Échéancier flexible",
    "c_form_urgency_2": "D'ici 1 à 2 semaines",
    "c_form_urgency_3": "D'ici 1 mois",
    "c_form_urgency_4": "2 à 3 mois",
    "c_form_urgency_5": "Dès que possible",
    "c_form_label_deadline": "Date limite absolue (si applicable)",

    "form_sec_5_title": "Quel est votre budget ?",
    "c_form_label_budget": "Fourchette de budget <span class=\"required-star\">*</span>",
    "c_form_hint_budget": "Cela nous aide à dimensionner le projet de manière appropriée. Nous en discuterons lors de notre appel.",
    "c_form_err_budget": "Veuillez sélectionner une fourchette de budget",
    "c_form_budg_1": "Moins de 500 $",
    "c_form_budg_2": "500 $ - 1 000 $",
    "c_form_budg_3": "1 000 $ - 2 500 $",
    "c_form_budg_4": "2 500 $ - 5 000 $",
    "c_form_budg_5": "5 000 $ - 10 000 $",
    "c_form_budg_6": "Plus de 10 000 $",
    "c_form_budg_7": "Pas encore certain",

    "form_sec_6_title": "Autre chose ?",
    "c_form_label_add": "Détails supplémentaires ou questions",
    "c_form_hint_add": "Fichiers, contraintes, exigences particulières ou questions que vous avez pour nous.",
    "c_form_label_found": "Comment nous avez-vous trouvés ?",
    "c_form_found_1": "Moteur de recherche",
    "c_form_found_2": "Réseaux sociaux",
    "c_form_found_3": "Référence / Bouche-à-oreille",
    "c_form_found_4": "Client de retour",
    "c_form_found_5": "Événement / Conférence",
    "c_form_found_6": "Autre",

    "c_form_btn_text": "Envoyer le dossier de projet",
    "c_form_btn_loading": "Envoi en cours...",
    "c_form_disclaimer": "En soumettant, vous acceptez notre <a href=\"privacy.html\">Politique de confidentialité</a>.",
  }
};

document.addEventListener('DOMContentLoaded', () => {
  // Determine language, default to 'en'
  let currentLang = localStorage.getItem('collarwork_lang') || 'en';
  setLanguage(currentLang);

  // Setup toggle button
  const toggleBtn = document.getElementById('lang-toggle');
  if (toggleBtn) {
    toggleBtn.addEventListener('click', (e) => {
      e.preventDefault();
      currentLang = currentLang === 'en' ? 'fr' : 'en';
      setLanguage(currentLang);
    });
  }
});

function setLanguage(lang) {
  // Store preference
  localStorage.setItem('collarwork_lang', lang);
  document.documentElement.lang = lang === 'en' ? 'en' : 'fr-CA';

  // Translate all elements with data-i18n
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      // Use innerHTML because some translations contain `<br>` or `<i>` tags
      el.innerHTML = translations[lang][key];
    }
  });

  // Translate all elements with data-i18n-placeholder
  const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
  placeholders.forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (translations[lang] && translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  // Translate Meta Description
  const metaDesc = document.querySelector('meta[name="description"]');
  const ogDesc = document.querySelector('meta[property="og:description"]');
  const twitterDesc = document.querySelector('meta[property="twitter:description"]');
  if (metaDesc && translations[lang]["meta_desc"]) {
    metaDesc.content = translations[lang]["meta_desc"];
    if (ogDesc) ogDesc.content = translations[lang]["meta_desc"];
    if (twitterDesc) twitterDesc.content = translations[lang]["meta_desc"];
  }
}

